services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: idempotent-webhook-relay
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      STRIPE_SECRET_KEY: xxx
      STRIPE_WEBHOOK_SECRET: xxx
      GIN_MODE: release
    ports:
      - 3000:3000
    restart: unless-stopped
    networks:
      - privacy-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    ports:
      - 5432
    networks:
      - privacy-network
    restart: unless-stopped
    environment:
      POSTGRES_DB: idempotent-webhook-relay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d idempotent-webhook-relay"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - privacy-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

networks:
  privacy-network:
    driver: bridge

volumes:
  rabbitmq_data:
  rabbitmq_log:
