// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Outbox struct {
	ID            int32
	EventID       string
	Type          string
	Payload       []byte
	Status        pgtype.Text
	Provider      string
	RetryCount    int32
	LastError     pgtype.Text
	LastAttemptAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
